import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Brain, BookOpen, TrendingUp, Zap } from "lucide-react";

const Index = () => {
  const navigate = useNavigate();

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (session) {
        navigate("/dashboard");
      }
    });
  }, [navigate]);

  return (
    <div className="min-h-screen" style={{ background: 'var(--gradient-hero)' }}>
      <div className="container mx-auto px-6 py-20">
        <div className="text-center space-y-8 mb-16">
          <div className="inline-flex items-center gap-3 mb-4">
            <div className="w-20 h-20 rounded-full flex items-center justify-center bg-white/20 backdrop-blur-sm">
              <Brain className="h-10 w-10 text-white" />
            </div>
          </div>
          <h1 className="text-6xl md:text-7xl font-bold text-white mb-6">
            SmartQuizzer
          </h1>
          <p className="text-2xl text-white/90 max-w-3xl mx-auto leading-relaxed">
            Master any subject with AI-powered quizzes tailored to your skill level
          </p>
          <Button
            size="lg"
            className="px-12 py-7 text-xl font-semibold shadow-2xl hover:scale-105 transition-all bg-white text-primary hover:bg-white/90"
            onClick={() => navigate("/auth")}
          >
            Get Started
          </Button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-5xl mx-auto mt-20">
          <div className="bg-white/10 backdrop-blur-md p-8 rounded-2xl text-center space-y-4 hover:bg-white/20 transition-all">
            <div className="w-16 h-16 rounded-full bg-white/20 flex items-center justify-center mx-auto">
              <Zap className="h-8 w-8 text-white" />
            </div>
            <h3 className="text-2xl font-bold text-white">AI-Generated</h3>
            <p className="text-white/80 leading-relaxed">
              Dynamic questions generated by advanced AI for unique quiz experiences every time
            </p>
          </div>

          <div className="bg-white/10 backdrop-blur-md p-8 rounded-2xl text-center space-y-4 hover:bg-white/20 transition-all">
            <div className="w-16 h-16 rounded-full bg-white/20 flex items-center justify-center mx-auto">
              <BookOpen className="h-8 w-8 text-white" />
            </div>
            <h3 className="text-2xl font-bold text-white">Multi-Subject</h3>
            <p className="text-white/80 leading-relaxed">
              Choose from Mathematics, Science, Computer Science, and more specialized topics
            </p>
          </div>

          <div className="bg-white/10 backdrop-blur-md p-8 rounded-2xl text-center space-y-4 hover:bg-white/20 transition-all">
            <div className="w-16 h-16 rounded-full bg-white/20 flex items-center justify-center mx-auto">
              <TrendingUp className="h-8 w-8 text-white" />
            </div>
            <h3 className="text-2xl font-bold text-white">Track Progress</h3>
            <p className="text-white/80 leading-relaxed">
              Monitor your performance with detailed analytics and subject-wise insights
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Index;
